/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WipesRouteImport } from './routes/wipes'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadStaticSiteRouteImport } from './routes/api.download.static-site'

const WipesRoute = WipesRouteImport.update({
  id: '/wipes',
  path: '/wipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadStaticSiteRoute = ApiDownloadStaticSiteRouteImport.update({
  id: '/api/download/static-site',
  path: '/api/download/static-site',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
  '/wipes': typeof WipesRoute
  '/api/download/static-site': typeof ApiDownloadStaticSiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
  '/wipes': typeof WipesRoute
  '/api/download/static-site': typeof ApiDownloadStaticSiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/rules': typeof RulesRoute
  '/wipes': typeof WipesRoute
  '/api/download/static-site': typeof ApiDownloadStaticSiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/history'
    | '/profile'
    | '/rules'
    | '/wipes'
    | '/api/download/static-site'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/history'
    | '/profile'
    | '/rules'
    | '/wipes'
    | '/api/download/static-site'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/history'
    | '/profile'
    | '/rules'
    | '/wipes'
    | '/api/download/static-site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  HistoryRoute: typeof HistoryRoute
  ProfileRoute: typeof ProfileRoute
  RulesRoute: typeof RulesRoute
  WipesRoute: typeof WipesRoute
  ApiDownloadStaticSiteRoute: typeof ApiDownloadStaticSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wipes': {
      id: '/wipes'
      path: '/wipes'
      fullPath: '/wipes'
      preLoaderRoute: typeof WipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/static-site': {
      id: '/api/download/static-site'
      path: '/api/download/static-site'
      fullPath: '/api/download/static-site'
      preLoaderRoute: typeof ApiDownloadStaticSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  HistoryRoute: HistoryRoute,
  ProfileRoute: ProfileRoute,
  RulesRoute: RulesRoute,
  WipesRoute: WipesRoute,
  ApiDownloadStaticSiteRoute: ApiDownloadStaticSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
